name = "MUSCLE"
uuid = "7ae5a178-6e0c-4685-bb5d-85668ef53397"
authors = ["Michael Persico <michael.a.persico@gmail.com> and contributors"]
version = "0.1.0-alpha"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
MUSCLE_jll = "0d2b832c-22e5-5080-b34f-49cc6141c4c5"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.6"
